MyProject.Core/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyProject.Core.Library.UnitOfWork;

namespace MyProject.Core.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class BaseController : Controller
    {
        protected IUnitOfWork Uow { get; set; }
    }
}

MyProject.Core/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyProject.Core.Models;

namespace MyProject.Core.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

MyProject.Core/Controllers/Security/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyProject.Core.Library.Models;
using MyProject.Core.Library.UnitOfWork;

namespace MyProject.Core.Controllers.Security
{
    [ApiController]
    [Produces("application/json")]
    [Route("api/Security")]
    public class SecurityController : BaseController
    {
        IDataProtector _iDP;
        public SecurityController(IUnitOfWork uow, IDataProtectionProvider dataProtectionProvider)
        {
            Uow = uow;
            _iDP = dataProtectionProvider.CreateProtector("SecurityClass");
        }
        [HttpGet("GetAll")]
        public async Task<IEnumerable<Bank>> GetAll()
        {
            //var remoteIpAddress = Request.UserHostAddress;
            string name = "ABC";
            string proString = _iDP.Protect(name); //Microsoft Encryption Method for data security;
            string DString = _iDP.Unprotect(proString);
            var q = await Uow._Bank.GetAll();
            return q;
            
        }
    }
}

MyProject.Core/Controllers/SetUp/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Management;
using System.Net;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyProject.Core.Library.Models;
using MyProject.Core.Library.UnitOfWork;
using Microsoft.AspNetCore.DataProtection;
namespace MyProject.Core.Controllers.SetUp
{
    [ApiController]
    [Produces("application/json")]
    [Route("api/Bank")]
    
    public class BankController : BaseController
    {
        IDataProtector _iDP;
        public BankController(IUnitOfWork uow, IDataProtectionProvider dataProtectionProvider)
        {
            Uow = uow;
            _iDP = dataProtectionProvider.CreateProtector("BanKClass");
        }
        /// <summary>
        /// Get:: /api/bank/Getall
        /// </summary>
        /// <returns></returns>
        /// 
        
        [HttpGet("GetAll")]
        public async Task<IEnumerable<Bank>> GetAll()
        {
            //var remoteIpAddress = Request.UserHostAddress;
            var mac = GetMACAddress();
            var ip = GetIPAddress();
            string name = "ABC";
            string proString = _iDP.Protect(name); //Microsoft Encryption Method for data security;
            string DString = _iDP.Unprotect(proString);
            var q = await Uow._Bank.GetAll();
            return q;
        }
        public string GetMACAddress()
        {
            ManagementObjectSearcher searcher = new ManagementObjectSearcher("SELECT * FROM Win32_NetworkAdapterConfiguration where IPEnabled=true");
            IEnumerable<ManagementObject> objects = searcher.Get().Cast<ManagementObject>();
            string mac = (from o in objects orderby o["IPConnectionMetric"] select o["MACAddress"].ToString()).FirstOrDefault();
            //lblMacId.Text = mac;

            NetworkInterface[] nics = NetworkInterface.GetAllNetworkInterfaces();
            String sMacAddress = string.Empty;
            foreach (NetworkInterface adapter in nics)
            {
                if (sMacAddress == String.Empty)// only return MAC Address from first card  
                {
                    IPInterfaceProperties properties = adapter.GetIPProperties();
                    sMacAddress = adapter.GetPhysicalAddress().ToString();
                }
            }
            IFormatProvider theCultureInfo = new System.Globalization.CultureInfo("en-GB", true);
            string dt = Convert.ToDateTime(DateTime.Now, theCultureInfo).ToString("MM-dd-yyyy hh:mm tt");
            return sMacAddress;

        }
        public string GetIPAddress()
        {
            string ip = String.Empty;
            IPHostEntry Host = default(IPHostEntry);
            string Hostname = null;
            Hostname = System.Environment.MachineName;
            Host = Dns.GetHostEntry(Hostname);
            foreach (IPAddress IP in Host.AddressList)
            {
                if (IP.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork)
                {
                    ip = Convert.ToString(IP);
                }
            }
            return ip;
        }
       
    }
}

MyProject.Core/Controllers/SetUp/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyProject.Core.Library.UnitOfWork;

namespace MyProject.Core.Controllers.SetUp
{
    //    [ApiController]
    //    [Produces("application/json")]
    [Route("api/Common")]
    public class CommonController : BaseController
    {
        protected IUnitOfWork Uow;
        public CommonController(IUnitOfWork uow)
        {
            this.Uow = uow;
        }
        // GET: Sales
        public ActionResult Bank()
        {
           
            
                return View();
            
        }
    }
}

MyProject.Core/Controllers/SetUp/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MyProject.Core.Controllers.SetUp
{
    [Route("api/[controller]")]
    [ApiController]
    public class LogInController : ControllerBase
    {
    }
}

MyProject.Core/Controllers/SetUp/SetUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyProject.Core.Controllers.SetUp
{
    public class SetUpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Bank()
        {
            return View();
        }

        public IActionResult LogIn()
        {
            return View();
        }
    }
}

MyProject.Core/Pages/Common/Bank.cshtml
@model IEnumerable<MyProject.Core.Library.Models.Bank>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Bank</title>
</head>
<body>
<div>
      
</div>
</body>
</html>

MyProject.Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyProject.Core/Views/SetUp/Bank.cshtml
@{
    ViewData["Title"] = "Bank";
}

<h1>Bank</h1>

MyProject.Core/Views/SetUp/LogIn.cshtml
@page
@model MyProject.Core.LogInModel
@{
    Layout = null;
}



<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Let's Start</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100" style="background-image: url('images/bg-01.jpg');">
            <div class="wrap-login100 p-t-30 p-b-50">
                <span class="login100-form-title p-b-41">
                    Account Login
                </span>
                <form class="login100-form validate-form p-b-33 p-t-5">

                    <div class="wrap-input100 validate-input" data-validate="Enter username">
                        <input class="input100" type="text" name="username" id="UserId" placeholder="User name">
                        <span class="focus-input100" data-placeholder="&#xe82a;"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Enter password">
                        <input class="input100" type="password" name="pass" id="Password" placeholder="Password">
                        <span class="focus-input100" data-placeholder="&#xe80f;"></span>
                    </div>

                    <div class="container-login100-form-btn m-t-32">
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>

                </form>
            </div>
        </div>
    </div>


    <div id="dropDownSelect1"></div>


    <!--===============================================================================================-->
    <script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/bootstrap/js/popper.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/js/main.js"></script>
    <script>
        $(function () {
            debugger;
            $('#UserId').bind("cut copy paste", function (e) {
                e.preventDefault();
            });
            $('#Password').bind("cut copy paste", function (e) {
                e.preventDefault();
            });
            $(".input100").bind("keypress", function (e) {
                var keyCode = e.which ? e.which : e.keyCode
                debugger;
                if ((keyCode == 59 || keyCode == 61 || keyCode == 92 || keyCode == 124 || keyCode==39)) {
                    return false;
                } 
            });
        });
    </script>
</body>
</html>

MyProject.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyProject.Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyProject.Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SetUp" asp-action="Bank">Bank</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MyProject.Core - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>